service: users
frameworkVersion: '3'

custom:
  usersTableName: 'users-table-${sls:stage}'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:BatchWriteItem
            - dynamodb:PutItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.usersTableName}

functions:
  ingestUsers:
    handler: handler.ingest
    events:
      - s3:
          bucket: ${construct:users.bucketName}
          existing: true

constructs:
    users:
        type: storage

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.usersTableName}

plugins:
  - serverless-lift
